#!/bin/sh

DELIMITER="  "
LOGPATH="/tmp/dwmbarlog"

MAIN() {
	case "$1" in
		TIMEDATE)
			TIMEDATE "$2"
			;;
		DFROOT)
			DFROOT "$2"
			;;
		DFFILES)
			DFFILES "$2"
			;;
		VOLUME)
			VOLUME "$2"
			;;
	esac
}

TIMEDATE_FETCH() {
	LOG "Fetching TIMEDATE..."
	[ ! -p /tmp/dwmbar ] && mkfifo /tmp/dwmbar && LOG "mkfifo"
	echo -e "DWMBAR_TIMEDATE=\"$(date '+%Y-%m-%d;%H:%M')"\" >> /tmp/dwmbar
	LOG "TIMEDATE fetched."
	exit
}

TIMEDATE_PRINT() {
	if [ -n "$DWMBAR_TIMEDATE" ]; then
		TIME="$(echo $DWMBAR_TIMEDATE | sed 's/^.*;//')"
		DATE="$(echo $DWMBAR_TIMEDATE | sed 's/;.*//')"
		echo -ne "\x02 $DATE$DELIMITER\x01 $TIME"
	else
		LOG "!TIMEDATE"
	fi
}

TIMEDATE() {
	case "$1" in
		--fetch)
			TIMEDATE_FETCH
			;;
		*)
			TIMEDATE_PRINT
			;;
	esac
}

DFROOT_FETCH() {
	LOG "Fetching DFROOT..."
	[ ! -p /tmp/dwmbar ] && mkfifo /tmp/dwmbar && LOG "mkfifo"
	DWMBAR_DFROOT="$(df -h / | awk 'NR==2 {print $4}')"
	echo -e "DWMBAR_DFROOT=\"$DWMBAR_DFROOT\"" >> /tmp/dwmbar
	LOG "DFROOT fetched."
	exit
}

DFROOT_PRINT() {
	if [ -n "$DWMBAR_DFROOT" ]; then
		echo -ne "\x03 $DWMBAR_DFROOT"
	else
		LOG "!DFROOT"
	fi
}

DFROOT() {
	case "$1" in
		--fetch)
			DFROOT_FETCH
			;;
		*)
			DFROOT_PRINT
			;;
	esac
}

DFFILES_FETCH() {
	LOG "Fetching DFFILES..."
	[ ! -p /tmp/dwmbar ] && mkfifo /tmp/dwmbar && LOG "mkfifo"
	DWMBAR_DFFILES="$(df -h ~/files | awk 'NR==2 {print $4}')"
	echo -e "DWMBAR_DFFILES=\"$DWMBAR_DFFILES\"" >> /tmp/dwmbar
	LOG "DFFILES fetched."
	exit
}

DFFILES_PRINT() {
	if [ -n "$DWMBAR_DFFILES" ]; then
		echo -ne "\x04 $DWMBAR_DFFILES"
	else
		LOG "!DFFILES"
	fi
}

DFFILES() {
	case "$1" in
		--fetch)
			DFFILES_FETCH
			;;
		*)
			DFFILES_PRINT
			;;
	esac
}

VOLUME_FETCH() {
	LOG "Fetching VOLUME..."
	[ ! -p /tmp/dwmbar ] && mkfifo /tmp/dwmbar && LOG "mkfifo"
	while true; do
		DWMBAR_VOLUME="$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')"
		[ -n "$DWMBAR_VOLUME" ] && break
		LOG "waiting VOLUME..."
		sleep 1;
	done
	echo -e "DWMBAR_VOLUME=\"$DWMBAR_VOLUME\"" >> /tmp/dwmbar
	LOG "VOLUME fetched."
	exit
}

VOLUME_PRINT() {
	if [ -n "$DWMBAR_VOLUME" ]; then
		echo -ne "\x05 $DWMBAR_VOLUME"
	else
		LOG "!VOLUME"
	fi
}

VOLUME() {
	case "$1" in
		--fetch)
			VOLUME_FETCH
			;;
		*)
			VOLUME_PRINT
			;;
	esac
}

IMPORT_FIFO() {
	if [ ! -p /tmp/dwmbar ]; then
		xsetroot -name "cant find /tmp/dwmbar!"
		LOG "cant find /tmp/dwmbar!"
		exit
	else
		LOG "importing /tmp/dwmbar..."
		source /tmp/dwmbar
		LOG ".../tmp/dwmbar imported."
	fi
}

BAR() {
	BAR="$(TIMEDATE)"
	BAR="$(DFROOT)$DELIMITER$BAR"
	BAR="$(DFFILES)$DELIMITER$BAR"
	BAR="$(VOLUME)$DELIMITER$BAR"
	echo "$BAR"
}

LOG() {
	echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> $LOGPATH
	echo "$1"
}

MAIN "$@"

if mkdir /tmp/dwmbar.lock >/dev/null 2>&1; then
	LOG "Starting dwmbar main loop..."
	xsetroot -name "Starting dwmbar main loop..."
	[ ! -p /tmp/dwmbar ] && mkfifo /tmp/dwmbar
	while [ -d /tmp/dwmbar.lock ]; do
		IMPORT_FIFO
		xsetroot -name "$(BAR)"
	done
	LOG "exiting dwmbar"
	exit
else
	LOG "dwmbar is already running!"
fi
