#!/bin/sh

DELIMITER="  "

add() {
	if [ "$1" = "-d" ]; then
		BAR="$2$DELIMITER$BAR"
	else
		BAR="$1$BAR"
	fi
}

TIME() {
	if [ -n "$DWMBAR_TIME" ]; then
		echo -ne "\x01 $DWMBAR_TIME"
	else
		echo -ne "\x01 !E"
	fi
}

[ "$(pgrep -xc dwmbar)" -ge 2 ] && echo "dwmbar is already running" && exit 1

while true; do
	BAR=""
	add "$(TIME)"
	xsetroot -name "$BAR"
	sleep 1;
done
